kind: ConfigMap
apiVersion: v1
metadata:
  name: my-configmap
  namespace: default
  labels:            ## aqui define qual label
    app: my-deployment-configmap
data:     ## aqui define os dados que o configmap vai ter todas as variaveis de ambiente de uma aplicaçaõ podem ser setadas aqui
  key: default