apiVersion: v1  #// This is the API version of the Kubernetes object
kind: Pod   #// This is the type of the Kubernetes object
metadata: 
  name: myfirstpod  #// This is the name of the pod
  labels:
    name: myfirstpod  #// This is the label of the pod for identification with filter
spec:
  containers:  #// This is the list of containers that will run in the pod
  - name: nameByContainer  #// This is the name of the container
    image: nginx #// This is the image that will be used to create the container dockerhub
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80  #// This is the port that the container will use
