kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: myclusterkind-ha  #cluster com alta disponibilidade
nodes:
- role: control-plane
- role: control-plane
  # image:  kindest/node:v1.30.0@sha256:047357ac0cfea04663786a612ba1eaba9702bef25227a794b52890dd8bcd692e
- role: control-plane
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
- role: worker
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8081
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
- role: worker
- role: worker