apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-deployment
  labels:
    name: labelDeployment
spec:    
  replicas: 3
  selector:
    matchLabels:
      app: labelDeployment
  template:
    metadata:
      labels:
        app: labelDeployment
    spec:    
      containers:
      - name:  my-aplication
        image:  nginx
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport  
spec:
  selector:
    app: labelDeployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort          
